### ISSUE TITLE
PIL 画图报错

### ISSUE THREAD

**Issue by shibing624** [twang2218/model-vocab-check#1]
PIL image draw 画图报错，原因是本地无中文字体，可以写英文到图片里面，不用安装中文字体了。

加几个建议：
1. `charset.json`集成到pip里，默认指定就可以，一般不会变；
2. 图片太大，可以压缩到几kb再上传；
3. PIL image draw 文字全改为英文，不依赖中文字体，日志打中文就行。

报错信息：
```
Traceback (most recent call last):
  File "/apdcephfs_cq3/share_2973545/flemingxu/nlp/vocab-coverage/vocab_coverage/main.py", line 50, in <module>
    main()
  File "/apdcephfs_cq3/share_2973545/flemingxu/nlp/vocab-coverage/vocab_coverage/main.py", line 40, in main
    model_check(args.model_name, charsets, args.output_dir, args.debug)
  File "/apdcephfs_cq3/share_2973545/flemingxu/nlp/vocab-coverage/vocab_coverage/model.py", line 120, in model_check
    draw_vocab_graph(model_name, charset_stats, tokenizer.vocab_size, filename, width=150)
  File "/apdcephfs_cq3/share_2973545/flemingxu/nlp/vocab-coverage/vocab_coverage/draw.py", line 100, in draw_vocab_graph
    draw.text(
  File "/data/flemingxu/soft/miniconda3/envs/py3.10/lib/python3.10/site-packages/PIL/ImageDraw.py", line 468, in text
    return self.multiline_text(
  File "/data/flemingxu/soft/miniconda3/envs/py3.10/lib/python3.10/site-packages/PIL/ImageDraw.py", line 600, in multiline_text
    line_width = self.textlength(
  File "/data/flemingxu/soft/miniconda3/envs/py3.10/lib/python3.10/site-packages/PIL/ImageDraw.py", line 735, in textlength
    return font.getlength(text, mode, direction, features, language)
  File "/data/flemingxu/soft/miniconda3/envs/py3.10/lib/python3.10/site-packages/PIL/ImageFont.py", line 198, in getlength
    width, height = self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-12: ordinal not in range(256)

```

**Comment by shibing624** [comment]
embedding 好像还是要中文输出词表

**Comment by twang2218** [comment]
字体的问题，可以安装一下 fonts-noto-cjk fonts-anonymous-pro 字体。

如果是 ubuntu 的话可以：

```bash
apt install fonts-noto-cjk fonts-anonymous-pro
```

macOS 的话，可以用 homebrew

```bash
brew install font-noto-sans-cjk font-noto-serif-cjk font-anonymous-pro
```

依赖字体的安装，我稍后加到 README 里去。

字体应该还是需要的，model字表覆盖率的图还好一些，下面需要列出不同字表的名称，这部分是中文，用英文也不是不可以，我可以加个参数，或者提示啥的，变成纯英文的图；但是 embedding 的图就没有办法了，因为要在图中画每个token，token中有大量中文，如果全用方块来代替就失去了查看语义关系的意义了，除非目的就是为了生成一个小的缩略图，token用点来表示那种。

稍后我找时间增加一个不依赖中文的生成缩略图的选项，来解决这个问题。

**Comment by Yahuicai** [comment]
> 字体的问题，可以安装一下 fonts-noto-cjk fonts-anonymous-pro 字体。
> 
> 如果是 ubuntu 的话可以：
> 
> ```shell
> apt install fonts-noto-cjk fonts-anonymous-pro
> ```
> 
> macOS 的话，可以用 homebrew
> 
> ```shell
> brew install font-noto-sans-cjk font-noto-serif-cjk font-anonymous-pro
> ```
> 
> 依赖字体的安装，我稍后加到 README 里去。
> 
> 字体应该还是需要的，model字表覆盖率的图还好一些，下面需要列出不同字表的名称，这部分是中文，用英文也不是不可以，我可以加个参数，或者提示啥的，变成纯英文的图；但是 embedding 的图就没有办法了，因为要在图中画每个token，token中有大量中文，如果全用方块来代替就失去了查看语义关系的意义了，除非目的就是为了生成一个小的缩略图，token用点来表示那种。
> 
> 稍后我找时间增加一个不依赖中文的生成缩略图的选项，来解决这个问题。

你好，我在ubuntu 中安装fonts-anonymous-pro字体遇到了报错，
E: Unable to locate package fonts-anonymous-pro。
我尝试了以下代码将字体手动安装在目录，安装后依然会报错，UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-12: ordinal not in range(256)。
请问这个字体应该怎么正确安装呢？谢谢

安装字体代码如下
`# 下载字体
wget https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1_002.zip

# 解压字体文件
unzip AnonymousPro-1_002.zip

# 创建字体目录（如果它不存在的话）
mkdir -p ~/.fonts

# 移动字体文件到字体目录
mv AnonymousPro-1.002.001/*.ttf ~/.fonts/

# 更新字体缓存
fc-cache -f -v
`
